require('basic')
require('keybindings')
require('plugins')
require('colorscheme')
require('plugin-config.nvim-tree')
require('plugin-config.bufferline')
require('plugin-config.lualine')
require('plugin-config.telescope')
require('plugin-config.dashboard')
require('plugin-config.project')
require('plugin-config.nvim-treesitter')
require('lsp.setup')
-- 内置LSP
require("lsp.cmp")
require("lsp.ui") -- 新增
require('lsp.vimtex')
-- vim.cmd('source ~/.config/nvim/lua/plugin-config/vimtex.vim')
